# Generated by Django 4.2.2 on 2023-10-04 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('data_created', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('steps', models.TextField(blank=True, max_length=2000, null=True)),
                ('ingredients', models.TextField(blank=True, max_length=2000, null=True)),
                ('like', models.PositiveIntegerField(blank=True, default=0)),
                ('mark', models.PositiveIntegerField(blank=True, default=0)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='recipe/')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile')),
                ('tags', models.ManyToManyField(blank=True, to='recipe.tags')),
            ],
            options={
                'ordering': ['-like', '-mark'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, max_length=1000, null=True)),
                ('value', models.CharField(choices=[('up', 'Нравится'), ('down', 'Не нравится')], max_length=100)),
                ('mark', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=100)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.recipe')),
            ],
            options={
                'unique_together': {('owner', 'recipe')},
            },
        ),
    ]
